FROM ruby:2.7.0-alpine

# List of folders on not required for production
ARG FOLDERS_TO_REMOVE="spec node_modules vendor/assets lib/assets tmp/cache"

RUN apk add --update --no-cache \
      binutils-gold \
      build-base \
      curl \
      file \
      g++ \
      gcc \
      git \
      less \
      libstdc++ \
      libffi-dev \
      libc-dev \
      linux-headers \
      libxml2-dev \
      libxslt-dev \
      libgcrypt-dev \
      make \
      netcat-openbsd \
      nodejs \
      openssl \
      pkgconfig \
      postgresql-dev \
      python \
      tzdata \
      yarn

RUN apk update && apk add bash

RUN gem install bundler -v 2.1.4

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle config build.nokogiri --use-system-libraries

RUN bundle check || bundle install

COPY . ./

RUN rm -rf $FOLDERS_TO_REMOVE

ENTRYPOINT ["sh", "./docker/app/docker-entrypoint.sh"]